### PR TITLE
Add export options

### PR DESCRIPTION
**Pull request by jwilliamrozelle**
* Add option for decryption with pem_key
* Add option for pull_before
* Add option for (includeGeo)
* change from the sep = "" argument to slightly more efficient paste0
* Add @param documentation for new options
* re-run roxygenize()
* increment version number in description

### CODE REVIEW

**Comment by ernestguevarra** [comment]
@jwilliamrozelle thanks for the pull request.

Everything seems to be in order though Travis and GitHub Actions still going.

I will merge this pull request once all checks go through. But before I do, can you amend the pull request to add your name to DESCRIPTION and assign yourself as contributor?

Also, do you have any inputs for testing the options you've provided? Would be good to add those eventually over time. All we'll need will be sample datasets from an ODK Aggregate that we can communicate with with encryption and with the Geo components. Let me know if you have any ideas for those.

**Comment by jwilliamrozelle** [comment]
Sure, happy to update the description!

I could add some inputs for testing - I saw that you're using a test server
on ONA. I could potentially add a dataset there that's encrypted, and
include a sample encryption key.

That shouldn't be too difficult. I separately sent an email a few minutes
ago introducing myself. Looks like there was 403 error for why it failed
the test - I don't think anything I edited should have caused that, but I
can look. Any thoughts?

I could add those in the next week or so.

Thanks,

*Jeffrey W. Rozelle, MPH*
Monitoring & Evaluation Professional
m: +1 (616) 951-1773 | skype: jwilliamrozelle

<https://figured.io>

**Comment by ernestguevarra** [comment]
The testing coverage is set in such a way that when something new is added without new testing parameters, it will alert me that testing coverage goes down. That's not a big issue. I am not particular about that failing. But ideally, and I myself am not good in following this, it would be good for new edits and new functions to come with a testing suite already.

For this project, since it got archived on CRAN, i have loosened up a bit on testing (hence the 50% coverage) and have just been finding time to get it up to high standards again.

Let's wait up on the testing. We can work on that better together over time, if you would like to further collaborate?

I have been splitting my efforts on developing another app that is more of an API interface to ONA and KoboToolbox - see https://github.com/rapidsurveys/okapi. I would like for `odkr` and `okapi` to sort of mature together.

**Comment by jwilliamrozelle** [comment]
Yes, I would be happy to further collaborate and contribute where helpful!

I'd been separately developing some things myself, but what you've got is
far more mature. I think my time would be better spent contributing and
supporting what you've already built, rather than re-building something
that already exists.

I'll push the updated odkr shortly - with an updated description.

*Jeffrey W. Rozelle, MPH*
Monitoring & Evaluation Professional
m: +1 (616) 951-1773 | skype: jwilliamrozelle

<https://figured.io>

**Comment by jwilliamrozelle** [comment]
apologies - made a minor mistake - please ignore this push, and will submit another in a few minutes

**Comment by jwilliamrozelle** [comment]
Okay - the latest push should be good. Forgot to re-run roxygenise, and caught a parenthesis mistake when I did.

**Comment by ernestguevarra** [comment]
@jwilliamrozelle I've merged this to master. Thanks for the pull request and contribution. Sorry for the delay as I was busy with lots of teaching the the past 4 days of this week.

**Comment by jwilliamrozelle** [comment]
No worries, thanks for the update!

**Pull request merged**
